backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.routes_view, name='routes'),
    path('<slug:slug>/', views.route_detail_view, name='route'),
]

backend/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

]

backend/order/urls.py
from django.urls import path
from order import views

app_name = 'order'

urlpatterns = [
    path('create_order/<int:event_id>/', views.create_order, name='create_order'),
]

backend/schedule/urls.py
from django.urls import path
from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('', views.index, name='index'),

]

backend/schedule/models.py
from datetime import timedelta, date
from django.db import models
from django.utils import timezone
from catalog.models import Route, Category

class Event(models.Model):
    """
    Модель для представления событий.

    Представляет информацию о проводимых мероприятиях, их статусе, категории, маршруте, цене, доступных местах и времени начала и конца.
    """
    STATUS_CHOICES = (
        ('Предстоит', 'Предстоит'),
        ('Идёт', 'Идёт'),
        ('Завершен', 'Завершен'),
        ('Отменен', 'Отменен'),
    )
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, default=None, verbose_name='Категория')
    route = models.ForeignKey(to=Route, on_delete=models.CASCADE,default=None, verbose_name='Маршрут')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Предстоит', verbose_name='Статус события')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    total_seats = models.PositiveSmallIntegerField(verbose_name='Всего мест', default=0)
    remaining_seats = models.PositiveIntegerField(verbose_name='Осталось мест', default=0) 
    start = models.DateTimeField(null=True, blank=True, verbose_name='Начало прогулки')
    end = models.DateTimeField(null=True, blank=True, verbose_name='Конец прогулки')
    
    class Meta:  
        db_table = 'tblevents'
        verbose_name = 'Прогулка'
        verbose_name_plural = 'Прогулки'

    def save(self, *args, **kwargs) -> None:
        """
        Метод сохранения события.

        Перед сохранением события убеждаемся, что поля start и end содержат информацию о часовом поясе.
        """
        if self.start is not None and timezone.is_naive(self.start):
            self.start = timezone.make_aware(self.start, timezone.get_current_timezone())
        if self.end is not None and timezone.is_naive(self.end):
            self.end = timezone.make_aware(self.end, timezone.get_current_timezone())
        super().save(*args, **kwargs)


    def __str__(self) -> str:
        """
        Возвращает строковое представление события.

        Returns:
            str: Строковое представление события.
        """
        return f'{self.route.name}: {self.start}'


class EventManager(models.Manager):
    def get_queryset(self, weeks: int = 2) -> models.QuerySet:
        """
        Метод для получения ближайших событий.

        :param weeks: количество недель для фильтрации событий (по умолчанию 2 недели)
        """
        start_date: date = timezone.now().date()
        end_date: date = start_date + timedelta(weeks=weeks)
        return super().get_queryset().filter(start__range=(start_date, end_date))


class EventProxy(Event):

    objects: EventManager = EventManager()

    class Meta:
        proxy: bool = True

backend/schedule/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseServerError
from django.db.models.query import QuerySet
from .models import EventProxy


def index(request) -> HttpResponse:
    """
    Отображает страницу с расписанием событий.

    Parameters:
        request (HttpRequest): HTTP-запрос.

    Returns:
        HttpResponse: HTTP-ответ с HTML-содержимым страницы расписания.

    Raises:
        ValidationError: Если параметры запроса недопустимы.
        Exception: Если произошла неизвестная ошибка.

    """
    try:
        category_slug = request.GET.get('category')
        time_start = request.GET.get('time_start')
        time_end = request.GET.get('time_end')
        min_price = request.GET.get('min_price')
        max_price = request.GET.get('max_price')

        events = get_filtered_events(category_slug, time_start, time_end, min_price, max_price)

        context = {
            'title': 'Расписание',
            'events': events,
            'category_slug': category_slug,
            'time_start': time_start,
            'time_end': time_end,
            'min_price': min_price,
            'max_price': max_price,
        }
        return render(request, 'shedule/schedule.html', context=context)
    except Exception as e:
        error_message = "Произошла ошибка: {}".format(str(e))
        return HttpResponseServerError(error_message)


def get_filtered_events(category_slug: str, time_start: str, time_end: str, min_price: str, max_price: str) -> QuerySet[EventProxy]:
    """
    Фильтрует события на основе предоставленных параметров.

    Parameters:
        category_slug (str): Слаг категории для фильтрации.
        time_start (str): Время начала для фильтрации.
        time_end (str): Время окончания для фильтрации.
        min_price (str): Минимальная цена для фильтрации.
        max_price (str): Максимальная цена для фильтрации.

    Returns:
        QuerySet[EventProxy]: Отфильтрованный набор данных событий.

    """
    events = EventProxy.objects.all().select_related('category')

    if category_slug and category_slug != 'all':
        events = events.filter(category__slug=category_slug)

    if time_start and time_end:
        events = filter_events_by_time(events, time_start, time_end)

    if min_price:
        events = events.filter(route__price__gte=min_price)
    if max_price:
        events = events.filter(route__price__lte=max_price)

    return events.order_by('start')


def filter_events_by_time(events: QuerySet[EventProxy], time_start: str, time_end: str) -> QuerySet[EventProxy]:
    """
    Фильтрует события по времени.

    Parameters:
        events (QuerySet[EventProxy]): Набор данных событий для фильтрации.
        time_start (str): Начальное время интервала для фильтрации.
        time_end (str): Конечное время интервала для фильтрации.

    Returns:
        QuerySet[EventProxy]: Отфильтрованный набор данных событий по времени.

    """
    if time_start and time_end is not None:
        if time_end < time_start:
            events = events.filter(start__time__gte=time_start) | events.filter(start__time__lte=time_end)
        else:
            events = events.filter(start__time__gte=time_start, start__time__lte=time_end)
    return events

backend/schedule/templates/shedule/demo.html
{% extends "base.html" %}
{% load catalog_tags %}
{% load tz %}

{% block content %}

<!-- Форма для фильтрации (скрытая на мобильной версии) -->
<div class="collapse d-md-none" id="filterCollapse">
    <form method="get" action="{% url 'schedule:index' %}" class="mb-3">
        <!-- Фильтры -->
        <div class="row">
            <!-- Фильтр по категории -->
            <div class="col-md-4 mb-2">
                <label for="category" class="form-label">Категория:</label>
                <select id="category" name="category" class="form-select">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <option value="{{ category.slug }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- Фильтр по времени начала -->
            <div class="col-md-4 mb-2">
                <label for="time_start" class="form-label">Начальное время:</label>
                <input type="time" id="time_start" name="time_start" class="form-control" value="{{ time_start }}">
            </div>

            <!-- Фильтр по времени конца -->
            <div class="col-md-4 mb-2">
                <label for="time_end" class="form-label">Конечное время:</label>
                <input type="time" id="time_end" name="time_end" class="form-control" value="{{ time_end }}">
            </div>
        </div>

        <!-- Фильтры по цене -->
        <div class="row">
            <div class="col-md-6 mb-2">
                <label for="min_price" class="form-label">Минимальная цена:</label>
                <input type="number" id="min_price" name="min_price" class="form-control" value="{{ min_price }}">
            </div>
            <div class="col-md-6 mb-2">
                <label for="max_price" class="form-label">Максимальная цена:</label>
                <input type="number" id="max_price" name="max_price" class="form-control" value="{{ max_price }}">
            </div>
        </div>

        <!-- Кнопка применить фильтры -->
        <div class="row justify-content-center">
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary w-100">Применить фильтры</button>
            </div>
        </div>
    </form>
</div>

<!-- Бургер кнопка для мобильной версии -->
<div class="d-md-none mb-3">
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
        Фильтры
    </button>
</div>

<!-- Форма для фильтрации (видимая на десктопах) -->
<form method="get" action="{% url 'schedule:index' %}" class="mb-3 d-none d-md-block">
    <!-- Фильтры -->
    <div class="row">
        <!-- Фильтр по категории -->
        <div class="col-md-4 mb-2">
            <label for="category" class="form-label">Категория:</label>
            <select id="category" name="category" class="form-select">
                {% tag_categories as categories %}
                {% for category in categories %}
                    <option value="{{ category.slug }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Фильтр по времени начала -->
        <div class="col-md-4 mb-2">
            <label for="time_start" class="form-label">Начальное время:</label>
            <input type="time" id="time_start" name="time_start" class="form-control" value="{{ time_start }}">
        </div>

        <!-- Фильтр по времени конца -->
        <div class="col-md-4 mb-2">
            <label for="time_end" class="form-label">Конечное время:</label>
            <input type="time" id="time_end" name="time_end" class="form-control" value="{{ time_end }}">
        </div>
    </div>

    <!-- Фильтры по цене -->
    <div class="row">
        <div class="col-md-6 mb-2">
            <label for="min_price" class="form-label">Минимальная цена:</label>
            <input type="number" id="min_price" name="min_price" class="form-control" value="{{ min_price }}">
        </div>
        <div class="col-md-6 mb-2">
            <label for="max_price" class="form-label">Максимальная цена:</label>
            <input type="number" id="max_price" name="max_price" class="form-control" value="{{ max_price }}">
        </div>
    </div>

    <!-- Кнопка применить фильтры -->
    <div class="row justify-content-center">
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary w-100">Применить фильтры</button>
        </div>
    </div>
</form>

<!-- Контент -->
<div class="event-grid-container mt-4">
    <button class="scroll-button prev-button" onclick="scrollLeft()">&#10094;</button>
    <div class="event-grid">
        {% regroup events by start|date as event_dates %}
        {% for date in event_dates %}
            <div class="event-column" style="flex-grow: 0.5;">
                <h3>{{ date.grouper }}</h3>
                {% for event in date.list %}
                    <div class="event">
                        <h4>{{ event.route.name }}</h4>
                        <p>Price: {{ event.route.price }}</p>
                        <p>Time: {{ event.start|timezone:"Europe/Moscow"|time }}</p>
                        <a href="{% url 'catalog:route' event.route.slug %}" class="btn btn-dark">More Info</a>
                        <p>    
                            <a class="btn btn-dark" href="{% url "order:create_order" event.id %}">   
                                {{event.start}}
                            </a>
                        </p>
                        </form>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <button class="scroll-button next-button" onclick="scrollRight()">&#10095;</button>
</div>

{% endblock %}

backend/schedule/templates/shedule/schedule.html
{% extends "base.html" %}
{% load catalog_tags %}
{% load tz %}

{% block content %}

<!-- Форма для фильтрации (скрытая на мобильной версии) -->
<div class="collapse d-md-none" id="filterCollapse">
    <form method="get" action="{% url 'schedule:index' %}" class="mb-3">
        <!-- Фильтры -->
        <div class="row">
            <!-- Фильтр по категории -->
            <div class="col-md-4 mb-2">
                <label for="category" class="form-label">Категория:</label>
                <select id="category" name="category" class="form-select">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <option value="{{ category.slug }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- Фильтр по времени начала -->
            <div class="col-md-4 mb-2">
                <label for="time_start" class="form-label">Начальное время:</label>
                <input type="time" id="time_start" name="time_start" class="form-control" value="{{ time_start }}">
            </div>

            <!-- Фильтр по времени конца -->
            <div class="col-md-4 mb-2">
                <label for="time_end" class="form-label">Конечное время:</label>
                <input type="time" id="time_end" name="time_end" class="form-control" value="{{ time_end }}">
            </div>
        </div>

        <!-- Фильтры по цене -->
        <div class="row">
            <div class="col-md-6 mb-2">
                <label for="min_price" class="form-label">Минимальная цена:</label>
                <input type="number" id="min_price" name="min_price" class="form-control" value="{{ min_price }}">
            </div>
            <div class="col-md-6 mb-2">
                <label for="max_price" class="form-label">Максимальная цена:</label>
                <input type="number" id="max_price" name="max_price" class="form-control" value="{{ max_price }}">
            </div>
        </div>

        <!-- Кнопка применить фильтры -->
        <div class="row justify-content-center">
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary w-100">Применить фильтры</button>
            </div>
        </div>
    </form>
</div>

<!-- Бургер кнопка для мобильной версии -->
<div class="d-md-none mb-3">
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
        Фильтры
    </button>
</div>

<!-- Форма для фильтрации (видимая на десктопах) -->
<form method="get" action="{% url 'schedule:index' %}" class="mb-3 d-none d-md-block">
    <!-- Фильтры -->
    <div class="row">
        <!-- Фильтр по категории -->
        <div class="col-md-4 mb-2">
            <label for="category" class="form-label">Категория:</label>
            <select id="category" name="category" class="form-select">
                {% tag_categories as categories %}
                {% for category in categories %}
                    <option value="{{ category.slug }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Фильтр по времени начала -->
        <div class="col-md-4 mb-2">
            <label for="time_start" class="form-label">Начальное время:</label>
            <input type="time" id="time_start" name="time_start" class="form-control" value="{{ time_start }}">
        </div>

        <!-- Фильтр по времени конца -->
        <div class="col-md-4 mb-2">
            <label for="time_end" class="form-label">Конечное время:</label>
            <input type="time" id="time_end" name="time_end" class="form-control" value="{{ time_end }}">
        </div>
    </div>

    <!-- Фильтры по цене -->
    <div class="row">
        <div class="col-md-6 mb-2">
            <label for="min_price" class="form-label">Минимальная цена:</label>
            <input type="number" id="min_price" name="min_price" class="form-control" value="{{ min_price }}">
        </div>
        <div class="col-md-6 mb-2">
            <label for="max_price" class="form-label">Максимальная цена:</label>
            <input type="number" id="max_price" name="max_price" class="form-control" value="{{ max_price }}">
        </div>
    </div>

    <!-- Кнопка применить фильтры -->
    <div class="row justify-content-center">
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary w-100">Применить фильтры</button>
        </div>
    </div>
</form>

<!-- Контент -->
<div class="event-grid-container mt-4">
    <button class="scroll-button prev-button" onclick="scrollLeft()">&#10094;</button>
    <div class="event-grid">
        {% regroup events by start|date as event_dates %}
        {% for date in event_dates %}
            <div class="event-column" style="flex-grow: 0.5;">
                <h3>{{ date.grouper }}</h3>
                {% for event in date.list %}
                    <div class="event">
                        <h4>{{ event.route.name }}</h4>
                        <p>Price: {{ event.route.price }}</p>
                        <p>Time: {{ event.start|timezone:"Europe/Moscow"|time }}</p>
                        <a href="{% url 'catalog:route' event.route.slug %}" class="btn btn-dark">More Info</a>
                        <p>    
                            <a class="btn btn-dark" href="{% url "order:create_order" event.id %}">   
                                {{event.start}}
                            </a>
                        </p>
                        </form>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <button class="scroll-button next-button" onclick="scrollRight()">&#10095;</button>
</div>

{% endblock %}