backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

]

backend/order/urls.py
from django.urls import path
from order import views

app_name = 'order'

urlpatterns = [
    path('create_order/<int:event_id>/', views.create_order, name='create_order'),
]

backend/order/models.py
from django.db import models
from schedule.models import Event


class BaseOrder(models.Model):
    """
    Абстрактная базовая модель заказа.

    Attributes:
        fullname (str): Имя заказчика.
        phone_number (str): Номер телефона заказчика.
        email (str): Адрес электронной почты заказчика.
        quantity (int): Количество заказанных товаров или услуг.
        payment_by_card (bool): Флаг оплаты картой.
        is_paid (bool): Флаг оплаченного заказа.
        status (str): Статус заказа (выбираемый из заданных вариантов).
        created_timestamp (datetime): Дата и время создания заказа.
        update_timestamp (datetime): Дата и время последнего обновления заказа.
    """

    STATUS = (
        ('Ждет подтверждения', 'Ждет подтверждения'),
        ('Подтвержден', 'Подтвержден'),
        ('Выполнен', 'Выполнен'),
        ('Отменен', 'Отменен'),
    )

    fullname = models.CharField(max_length=150, verbose_name='Имя')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    email = models.EmailField(verbose_name='Адрес почты')
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name='Количество')
    payment_by_card = models.BooleanField(default=False, verbose_name='Оплата картой')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=18, choices=STATUS, default='Ждет подтверждения', verbose_name='Статус заказа')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    update_timestamp = models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')

    class Meta:
        abstract = True

    def total_price(self):
        """
        Вычисляет общую стоимость заказа.

        Returns:
            float: Общая стоимость заказа.
        """
        pass

    def __str__(self):
        return f'Заказ № {self.pk} | Покупатель {self.fullname}: {self.phone_number}'


class EventOrder(BaseOrder):
    """
    Модель заказа для конкретного события.

    Attributes:
        event (Event): Связанное событие (прогулка).
    """

    event = models.ForeignKey(to=Event, on_delete=models.CASCADE, verbose_name='Прогулка')

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ\Прогулки'
        verbose_name_plural = 'Заказы\Прогулки'

    def total_price(self):
        """
        Вычисляет общую стоимость заказа на основе стоимости события и его количества.

        Returns:
            float: Общая стоимость заказа.
        """
        return round(self.event.price * self.quantity, 2)

    def __str__(self):
        return f'Прогулка : {self.event.route.name} | {self.event.start} |  Заказ № {self.pk}'

backend/order/forms.py
import re
from django import forms 
from django.core.exceptions import ValidationError
from .models import EventOrder

def validate_phone_number_format(value: str) -> None:
    """
    Валидатор для проверки формата номера телефона.
    Номер должен быть в формате XXX-XXX-XX-XX и состоять только из цифр.
    
    Args:
        value (str): Номер телефона для проверки.
        
    Raises:
        ValidationError: Если номер не соответствует формату.
    """
    if not value or not re.match(r'^\d{3}-\d{3}-\d{2}-\d{2}$', value):
        raise ValidationError('Номер телефона должен быть в формате XXX-XXX-XX-XX') 
    

class CreateOrderForm(forms.ModelForm):
    """
    Форма для создания заказа мероприятия.
    """
    class Meta:
        model = EventOrder
        fields = ('fullname', 'phone_number', 'email', 'quantity', 'payment_by_card',)

    payment_by_card = forms.ChoiceField(
        choices=[('0', 'False'), ('1', 'True')],
        widget=forms.RadioSelect,
    )

    def clean_quantity(self) -> int:
        """
        Проверяет количество мест на корректность.
        
        Returns:
            int: Количество мест.
        
        Raises:
            forms.ValidationError: Если количество мест не положительное число.
        """
        quantity = self.cleaned_data['quantity']
        if quantity <= 0:
            raise forms.ValidationError("Количество должно быть положительным числом.")
        return quantity

    def clean_payment_by_card(self) -> str:
        """
        Проверяет способ оплаты картой на корректность.
        
        Returns:
            str: Способ оплаты картой.
        
        Raises:
            forms.ValidationError: Если значение способа оплаты картой недопустимо.
        """
        payment_by_card = self.cleaned_data['payment_by_card']
        if payment_by_card not in ['0', '1']:
            raise forms.ValidationError("Недопустимое значение для оплаты картой.")
        return payment_by_card
    
    def clean_phone_number(self) -> str:
        """
        Проверяет формат номера телефона.
        
        Returns:
            str: Номер телефона.
        """
        phone_number = self.cleaned_data.get('phone_number')
        validate_phone_number_format(phone_number)
        return phone_number

backend/order/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.forms import ValidationError
from django.contrib import messages
from django.http import Http404
from django.utils import timezone

from order.models import EventOrder
from schedule.models import EventProxy
from order.forms import CreateOrderForm


def create_order(request, event_id: int = None) -> Any:
    """
    Отображает форму оформления заказа для указанного мероприятия.

    Args:
        request (HttpRequest): Объект HttpRequest, представляющий запрос.
        event_id (int, optional): ID мероприятия. По умолчанию None.

    Returns:
        HttpResponse: Возвращает отрендеренный шаблон или ответ перенаправления.

    Raises:
        Http404: Если мероприятие уже началось.

    """
    event = get_object_or_404(EventProxy, id=event_id)

    if event.start < timezone.now():
        raise Http404("Это мероприятие уже прошло и больше недоступно для заказа.")

    form = CreateOrderForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        try:
            with transaction.atomic():
                create_order_instance(event, form.cleaned_data)
                messages.success(request, 'Ваш заказ оформлен успешно!')
                return redirect('main:index')
        except ValidationError as e:
            messages.warning(request, e)

    context: Dict[str, Any] = {'title': 'Оформление заказа', 'form': form, 'event': event}
    return render(request, 'order/create_order.html', context=context)


def create_order_instance(event: EventProxy, cleaned_data: Dict[str, Any]) -> None:
    """
    Создает экземпляр EventOrder на основе предоставленных данных.

    Args:
        event (EventProxy): Мероприятие, для которого создается заказ.
        cleaned_data (Dict[str, Any]): Очищенные данные формы.

    Raises:
        ValidationError: Если для мероприятия недостаточно свободных мест.

    """
    if event.remaining_seats < cleaned_data['quantity']:
        raise ValidationError(f'На прогулке осталось {event.remaining_seats} мест.')

    order = EventOrder.objects.create(
        event=event,
        fullname=cleaned_data['fullname'],
        phone_number=cleaned_data['phone_number'],
        email=cleaned_data['email'],
        quantity=cleaned_data['quantity'],
        payment_by_card=cleaned_data['payment_by_card'],
    )

    event.remaining_seats -= order.quantity
    event.save()

backend/order/templates/order/create_order.html
{% extends "base.html" %}

{% block content %}

<div class="card mt-3">
    <div class="card-body">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-6">
                        <h3 class="card-title">{{ event.route.name }}</h3>
                        <p class="card-text">Дата: {{ event.start|date:"d.m.Y" }}</p>
                    </div>
                    <div class="col-md-6 text-end">
                        <p class="card-text">Время начала: {{ event.start|time:"H:i" }}</p>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12 d-flex justify-content-center align-items-center">
                    {% if event.route.image %}
                        <img src="{{ event.route.image.url }}" class="img-fluid rounded-start" alt="{{ event.route.name }}">
                    {% endif %}
                    </div>
                </div>
                <form action="{% url "order:create_order" event.id %}" method="post">
                    {% csrf_token %}
                    <div class="row mt-3">
                        <div class="col-md-12 text-center">
                            <p>Стоимость из расчета на 1 человека: {{ event.price }}</p>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <label for="id_fullname" class="form-label">Имя:</label>
                            <input type="text" class="form-control" id="id_fullname" name="fullname"
                                placeholder="Введите имя" value="{{ form.fullname.value|default_if_none:'' }}" required>
                            {% if form.fullname.errors %}
                                <div class="alert alert-danger">{{ form.fullname.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            <label for="id_phone_number" class="form-label">Номер телефона:</label>
                            <input type="tel" class="form-control" id="id_phone_number" name="phone_number"
                                placeholder="В формате: XXX-XXX-XX-XX" value="{{ form.phone_number.value|default_if_none:'' }}" required>
                            {% if form.phone_number.errors %}
                                <div class="alert alert-danger">{{ form.phone_number.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label for="id_email" class="form-label">Электронная почта:</label>
                            <input type="email" class="form-control" id="id_email" name="email"
                                placeholder="В формате: xxx@xx.xx" value="{{ form.email.value|default_if_none:'' }}" required>
                            {% if form.email.errors %}
                                <div class="alert alert-danger">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label for="id_quantity" class="form-label">Количество мест:</label>
                            <input type="number" class="form-control" step="1" min="1" max="100" id="id_quantity" name="quantity"
                                value="{{ form.quantity.value|default_if_none:'' }}" required>
                            {% if form.quantity.errors %}
                                <div class="alert alert-danger">{{ form.quantity.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="mb-3 mt-3">
                        <label class="form-label">Способ оплаты:</label>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="payment_by_card"
                                id="id_payment_by_card_1" value="0" checked>
                            <label class="form-check-label" for="id_payment_by_card_1">Оплата картой</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="payment_by_card"
                                id="id_payment_by_card_2" value="1">
                            <label class="form-check-label" for="id_payment_by_card_2">Наличными/картой при получении</label>
                        </div>
                        {% if form.payment_by_card.errors %}
                            <div class="alert alert-danger">{{ form.payment_by_card.errors }}</div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-dark">Оформить заказ</button>
                </form>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</div>

{% endblock %}