backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.routes_view, name='routes'),
    path('<slug:slug>/', views.route_detail_view, name='route'),
]

backend/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

]

backend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/my_css.css" %}">

    <!--Другие css оформления, footer, nav и т.д.-->
    {% block css %}  
    {% endblock  %}
    

    

    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu bg-primary">
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "catalog:routes" %}">Наши маршруты</a></li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url 'schedule:index' %}">Расписание</a></li>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Услуги
                            </a>
                            <ul class="dropdown-menu bg-primary">
                                <li><a class="dropdown-item  text-white" href="#">Прогулки</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Мероприятия</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Сертификаты</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    {% include "includes/notifications.html" %}
    <h1> {% block content %}
        Home - page
        {% endblock %}</h1>


    {% block footer %}
    {% endblock %}

    <script src="{% static 'js/filter.js' %}"></script>
    <script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "js/jquery-ajax.js" %}"></script>
    <script src="{% static "js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>
</html>